[2024-07-14T18:50:15.191+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T18:50:15.240+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: db_and_http.post_request manual__2024-07-14T18:50:02.242490+00:00 [queued]>
[2024-07-14T18:50:15.261+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: db_and_http.post_request manual__2024-07-14T18:50:02.242490+00:00 [queued]>
[2024-07-14T18:50:15.262+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-14T18:50:15.294+0000] {taskinstance.py:2330} INFO - Executing <Task(SimpleHttpOperator): post_request> on 2024-07-14 18:50:02.242490+00:00
[2024-07-14T18:50:15.301+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=960) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T18:50:15.303+0000] {standard_task_runner.py:63} INFO - Started process 961 to run task
[2024-07-14T18:50:15.303+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'db_and_http', 'post_request', 'manual__2024-07-14T18:50:02.242490+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/db_and_http_dag.py', '--cfg-path', '/tmp/tmp2l5z0ukv']
[2024-07-14T18:50:15.308+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask post_request
[2024-07-14T18:50:15.382+0000] {task_command.py:426} INFO - Running <TaskInstance: db_and_http.post_request manual__2024-07-14T18:50:02.242490+00:00 [running]> on host 26fab3728191
[2024-07-14T18:50:15.598+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='db_and_http' AIRFLOW_CTX_TASK_ID='post_request' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T18:50:02.242490+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T18:50:02.242490+00:00'
[2024-07-14T18:50:15.601+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T18:50:15.625+0000] {http.py:169} INFO - Calling HTTP method
[2024-07-14T18:50:15.647+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T18:50:15.663+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 166, in execute
    return self.execute_sync(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 170, in execute_sync
    response = self.hook.run(self.endpoint, self.data, self.headers, self.extra_options)
               ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 148, in hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `api_conn` isn't defined
[2024-07-14T18:50:15.682+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=db_and_http, task_id=post_request, run_id=manual__2024-07-14T18:50:02.242490+00:00, execution_date=20240714T185002, start_date=20240714T185015, end_date=20240714T185015
[2024-07-14T18:50:15.705+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task post_request (The conn_id `api_conn` isn't defined; 961)
[2024-07-14T18:50:15.733+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T18:50:15.754+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
  result = cls.__new__(cls)

[2024-07-14T18:50:15.788+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T18:50:15.794+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
